# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tree.fields
from tree.operations import CreateTreeTrigger


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_squashed_0008_item_state'),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='path',
            field=tree.fields.PathField(),
        ),
        CreateTreeTrigger('storage.Item'),
    ]
