# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_auto_20170215_0115"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("revision", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("path",)},
        ),
        migrations.AlterField(
            model_name="item",
            name="categories",
            field=models.ManyToManyField(blank=True, to="storage.Category"),
        ),
        migrations.AlterField(
            model_name="item",
            name="props",
            field=django_hstore.fields.DictionaryField(blank=True),
        ),
        migrations.AddField(
            model_name="label",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="storage.Item",
            ),
        ),
    ]
