# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
