# Generated by Django 3.2.20 on 2023-07-10 22:40

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension
from django.contrib.postgres.operations import TrigramExtension


# This migration is necessary for current production purposes.
# Technically is a no-op if extensions are turned on already.
class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_auto_20230710_1721"),
    ]

    operations = [
        HStoreExtension(),
        TrigramExtension(),
    ]
