# Generated by Django 3.2.20 on 2023-07-11 12:27

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension
from django.contrib.postgres.operations import TrigramExtension
from tree.operations import (
    DeleteTreeTrigger,
    CreateTreeTrigger,
    RebuildPaths,
)
from tree.fields import PathField


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0008_force_extensions_via_django"),
    ]

    operations = [
        DeleteTreeTrigger("storage.Item"),
        migrations.RemoveField("Item", "path"),
        migrations.AddField(
            model_name="item",
            name="path",
            field=PathField(db_index=True, order_by=["name"], size=None),
        ),
        CreateTreeTrigger("item"),
        RebuildPaths("item"),
    ]
