# Generated by Django 3.2.20 on 2023-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0011_auto_20230720_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="wiki_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
