# Generated by Django 5.0.1 on 2024-01-14 20:48

import storage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_item_wiki_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=storage.models.ImageFieldWithUuid(upload_to=''),
        ),
    ]
