version: "3"
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  web:
    image: registry.k0.hswaw.net/palid/spejstore:1689628039
    restart: always
    command: bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 --capture-output --error-logfile - --access-logfile - spejstore.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SPEJSTORE_CLIENT_ID
      - SPEJSTORE_SECRET
      - SPEJSTORE_ENV
