version: "2.3"
services:
  db:
    build: postgres-hstore
    restart: always
    volumes:
      - /var/spejstore-data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

    env_file:
      - spejstore-dev.env
      - spejstore.env
