version: "3"
services:
  web:
    environment:
      - SPEJSTORE_ENV=dev
      - SPEJSTORE_DB_NAME=postgres
      - SPEJSTORE_DB_USER=postgres
      - SPEJSTORE_DB_PASSWORD=postgres
      - SPEJSTORE_DB_HOST=db
      # - SPEJSTORE_DB_PORT=
      - SPEJSTORE_ALLOWED_HOSTS=localhost,127.0.0.1
      # - SPEJSTORE_CLIENT_ID=
      # - SPEJSTORE_SECRET=
      # - SPEJSTORE_MEDIA_ROOT=
      # - SPEJSTORE_REQUIRE_AUTH=true
