version: "3"
services:
  db:
    build: postgres-hstore
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 --capture-output --error-logfile - --access-logfile - spejstore.wsgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SPEJSTORE_CLIENT_ID
      - SPEJSTORE_SECRET
      - SPEJSTORE_ENV
