version: "3.4"
services:
  web:
    volumes:
      - ..:/workspaces:cached
    restart: unless-stopped

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - SPEJSTORE_ENV=dev
      - SPEJSTORE_DB_NAME=postgres
      - SPEJSTORE_DB_USER=postgres
      - SPEJSTORE_DB_PASSWORD=postgres
      - SPEJSTORE_DB_HOST=db
      # - SPEJSTORE_DB_PORT=
      - SPEJSTORE_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      # - SPEJSTORE_CLIENT_ID=
      # - SPEJSTORE_SECRET=
      # - SPEJSTORE_MEDIA_ROOT=
      # - SPEJSTORE_REQUIRE_AUTH=true
      - SPEJSTORE_OAUTH_REDIRECT_IS_HTTPS=false
      - SPEJSTORE_SPEJSTORE_FILE_STORAGE_TYPE="filesystem"
      # - SPEJSTORE_PROXY_TRUSTED_IPS=172.21.37.1
